### ISSUE TITLE
High-level shader generation

### ISSUE THREAD

**Issue by bil-bas** [Mon-Ouie/ray#21]
Writing shaders is effectively writing in C and although it is sometimes useful to optimise this, it is also useful, in the Ruby environment, to just be able to add effects easily.

I thought of 

``` Ruby
shader << Shader::Crop.new(100, 100, 500, 500)
shader << Shader::Pixelation([4, 4])
shader << Shader::Blur.new(2)

shader[:blur].disable # So I can re-enable it at a give point.
shader[:pixelation].factor = [8, 8]
```

Mon_ouie thought that using a more decoupled system to generate GLSL code would be better (the snippet was my suggestion as a way of doing this):

``` Ruby
shader.compile :frag => ShaderGenerator.new(crop: [...], pixelation: [...])
```

Does give you the advantage that you can just `puts` the generated code to learn how to write shaders, check it or generate it then hand-optimise it before use.

Alternatively, you could just abstract it out completely (why does anyone need to know that shaders are involved, any more than they need to know that rendering an image uses texture offsets).  This, however, would be a lot harder to integrate with user-modified shaders. This would also make it harder to specify the order of shader processes.

``` Ruby
window.blur = 5 # Would generate and compile a fragment shader that added blurring.
window.pixelation = 4 # Would re-write the shader to add pixelation to the blur effect.
window.blur = 0 # Would disable blur in the currently written shader.
```

**Comment by Mon-Ouie** [comment]
Since this API should ube realy nice to use, it'd be better to think about it for some time. ;)

I don't like the last suggestion because of the issues you mentioned. It's not flexible enough.

I think effects could simply define a uniform struct (in case you wouldn't know, GLSL has structs which are pretty similar to the ones you see in C). So, we could keep compatiblity with the current code and do this with a shader generated by `ShaderGenerator`:

``` ruby
shader["blur.enabled"] = true

# or perhaps to allow to use the same effect twice:
shader["blurs[0].enabled"] = true

shader["pixelation.factor"] = [8, 8]
```

Now, I wonder how effects would be created. First thinking about effects like those you described:

``` ruby
# Maybe calling them "effect" makes more sense?
class Pixelation < Ray::Effect
  attribute :factor, :vec2

  # allow to specify any type, as well as arrays
  attribute :thing, "custom_struct[3]"

  code <<-shader
    /* define our struct */
    struct custom_struct {
      /* ... */
    };

    vec4 pixelation(ray_pixelation args, vec4 color) {
       /* do work */
    }
  shader
end
```

This would work for effects that only need code in the fragment shader. This should cover most of them, but still, what about shaders that are meant to apply some transformations to vertices, or to generate geometry? Just completely ignoring them?

**Comment by bil-bas** [comment]
Structures do make a lot of sense to hold the data separate for each shading process. Can't think of a reason to have multiple runs through the same shader, but it might be better to just allow the user to set `name pixelation_2` in the odd case where they do multiples.

I'd probably further abstract with just having the `/* do work */` section manually written (the structure could be generated based on the attributes and the function template is a standard one).

**Comment by Mon-Ouie** [comment]
Gemerating the definition of `custom_struct` (!= `ray_pixelation`, in the example) can't be automated, unless I add a DSL to generate it too. Not wrapping the code between automatically generated names allows to define such structures as well as other functions if needed.

I think having the same effect several times could sometimes be usefeul, if the order matters. Not sure of an actual example for that.
